name = "IsoOrthoTensor"
uuid = "6490f2a6-240f-11e9-09ef-012bde3e15db"
authors = ["C. Naaktgeboren <NaaktgeborenC.PhD@gmail.com>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
